// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZXdshsaNjB-8GbZGr4xifVY0A0KsIvFI',
    appId: '1:858261065485:web:5b75af5108c756eef7ea44',
    messagingSenderId: '858261065485',
    projectId: 'login-signup-demo-763a2',
    authDomain: 'login-signup-demo-763a2.firebaseapp.com',
    storageBucket: 'login-signup-demo-763a2.appspot.com',
    measurementId: 'G-YVGQ8H6L7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL2GtbHHLUVNZOQv0eSYvC84-iHUqy8KI',
    appId: '1:858261065485:android:7d744662bdded7a0f7ea44',
    messagingSenderId: '858261065485',
    projectId: 'login-signup-demo-763a2',
    storageBucket: 'login-signup-demo-763a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3vhEUVhjULO0uRvDiRJU0Oxcx837dj5k',
    appId: '1:858261065485:ios:85da02142872bc27f7ea44',
    messagingSenderId: '858261065485',
    projectId: 'login-signup-demo-763a2',
    storageBucket: 'login-signup-demo-763a2.appspot.com',
    androidClientId: '858261065485-ujq1d892eit5ehgic7brasvcr6g7t9un.apps.googleusercontent.com',
    iosClientId: '858261065485-i6sj26kl51u50plv8lu56qevs2fcgl1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3vhEUVhjULO0uRvDiRJU0Oxcx837dj5k',
    appId: '1:858261065485:ios:85da02142872bc27f7ea44',
    messagingSenderId: '858261065485',
    projectId: 'login-signup-demo-763a2',
    storageBucket: 'login-signup-demo-763a2.appspot.com',
    androidClientId: '858261065485-ujq1d892eit5ehgic7brasvcr6g7t9un.apps.googleusercontent.com',
    iosClientId: '858261065485-i6sj26kl51u50plv8lu56qevs2fcgl1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZXdshsaNjB-8GbZGr4xifVY0A0KsIvFI',
    appId: '1:858261065485:web:6bc52c924b9db5f9f7ea44',
    messagingSenderId: '858261065485',
    projectId: 'login-signup-demo-763a2',
    authDomain: 'login-signup-demo-763a2.firebaseapp.com',
    storageBucket: 'login-signup-demo-763a2.appspot.com',
    measurementId: 'G-4E8C20S7HK',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAZXdshsaNjB-8GbZGr4xifVY0A0KsIvFI',
    appId: '1:858261065485:web:086ae610acc62383f7ea44',
    messagingSenderId: '858261065485',
    projectId: 'login-signup-demo-763a2',
    authDomain: 'login-signup-demo-763a2.firebaseapp.com',
    storageBucket: 'login-signup-demo-763a2.appspot.com',
    measurementId: 'G-PYWFLN2CPS',
  );
}
